services:
  db:
    image: postgres:latest
    env_file: ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "hbnb", "-d", "hbnb_v1"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge